!wip Add new project types system

diff --git a/create-module b/create-module
--- a/create-module
+++ b/create-module
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # -*- sh -*-
 # vim: syntax=sh
 # code: language=shellscript
@@ -7,6 +7,11 @@
 
 case "$-" in
 	(*'i'*)
+		if \command test -n "${BASH_VERSION-}"; then
+			# using `eval` here in case a non-Bash shell tries to parse this branch even if the condition is false
+			\command eval "\\command printf '%s: ' \"\${BASH_SOURCE[0]}\" >&2"
+		fi
+
 		\command printf 'script was called interactively\n' >&2
 		return 124
 		;;
@@ -18,11 +23,25 @@ set -o nounset
 # enabling POSIX-compliant behavior for GNU programs
 export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes
 
-if [ "${0#/}" = "$0" ]; then
+if [ -z "${BASH_VERSION-}" ]; then
+	if [ "${0#/}" = "$0" ]; then
+		argv0="$0"
+	else
+		argv0="$(basename -- "$0" && printf x)"
+		argv0="${argv0%"$(printf '\nx')"}"
+	fi
+	readonly argv0
+
+	printf '%s: GNU Bash is required for this script\n' "$argv0" >&2
+	exit 1
+fi
+
+declare argv0
+if [[ ! "$0" =~ ^'/' ]]; then
 	argv0="$0"
 else
 	argv0="$(basename -- "$0" && printf x)"
-	argv0="${argv0%"$(printf '\nx')"}"
+	argv0="${argv0%$'\nx'}"
 fi
 readonly argv0
 
@@ -30,26 +49,29 @@ readonly argv0
 
 #region args
 
-module_path_pattern='^(:[a-z][a-z0-9-]+)+$'
-readonly module_path_pattern
-
-print_usage() {
+function print_usage() {
 	printf 'usage: %s <module_path>...\n' "$argv0" >&2
 }
 
-if [ $# -eq 0 ]; then
+if (($# == 0)); then
 	printf '%s: missing arguments: <module_path>...\n' "$argv0" >&2
 	print_usage
 	exit 3
 fi
 
+declare module_path_pattern
+module_path_pattern='^(:[a-z][a-z0-9-]+)+$'
+readonly module_path_pattern
+
+declare -i i
 i=0
 
+declare arg
 for arg in "$@"; do
-	i=$((i + 1))
+	((++i))
 
 	if [ -z "$arg" ]; then
-		if [ $# -eq 1 ]; then
+		if (($# == 1)); then
 			printf '%s: argument must not be empty\n' "$argv0" >&2
 		else
 			printf '%s: argument %d: must not be empty\n' "$argv0" $i >&2
@@ -58,40 +80,181 @@ for arg in "$@"; do
 		exit 9
 	fi
 
-	if ! { printf '%s' "$arg" | grep -Eq -- "$module_path_pattern"; }; then
+	if ! [[ "$arg" =~ $module_path_pattern ]]; then
 		printf '%s: %s: does not match: %s\n' "$argv0" "$arg" "$module_path_pattern" >&2
 		exit 12
 	fi
 
-	if printf '%s' "$arg" | grep -Eq -- '--'; then
+	if [[ "$arg" =~ '--' ]]; then
 		printf '%s: %s: must not contain a substring of two consecutive dashes (--)\n' "$argv0" "$arg" >&2
 		exit 13
 	fi
-done; unset -v arg
+done
+unset -v arg
 
 unset -v i
 unset -f print_usage
 
 #endregion
 
+#region prompting for module types
+
+declare -a module_specs
+module_specs=()
+
+declare module_path
+for module_path in "$@"; do
+	{
+		printf "Select the type for module '%s'\\n" "$module_path"
+		printf '1) standalone\n'
+		printf '2) composite\n'
+		printf '3) namespace\n'
+		printf '4) service\n'
+		printf '5) service interface\n'
+		printf '6) service implementation (standalone)\n'
+		printf '7) service implementation (composite)\n'
+		printf '8) service wiring\n'
+	} >&2
+
+	while true; do
+		printf '> ' >&2
+
+		declare module_type
+		module_type=''
+
+		declare ans
+		read -r ans
+
+		case "$ans" in
+			(1) module_type='standalone' ;;
+			(2) module_type='composite' ;;
+			(3) module_type='namespace' ;;
+			(4) module_type='service' ;;
+			(5) module_type='service_interface' ;;
+			(6) module_type='service_implementation_standalone' ;;
+			(7) module_type='service_implementation_composite' ;;
+			(8) module_type='service_wiring' ;;
+		esac
+
+		unset -v ans
+
+		if [ -n "$module_type" ]; then
+			module_specs+=("$module_type:$module_path")
+			unset -v module_type
+			break
+		fi
+
+		unset -v module_type
+	done
+
+	printf '\n' >&2
+done
+
+readonly module_specs
+
+#endregion
+
+#region main
+
+declare root_dir_pathname
 root_dir_pathname="$(dirname -- "$0" && printf x)"
-root_dir_pathname="${root_dir_pathname%"$(printf '\nx')"}"
+root_dir_pathname="${root_dir_pathname%$'\nx'}"
 readonly root_dir_pathname
 
-gradle_build_file_template_pathname="$root_dir_pathname/module-templates/gradle.build.kts"
-readonly gradle_build_file_template_pathname
+function get_gradle_build_file_template_pathname_from_module_type() {
+	local module_type
+	module_type="$1"
+	readonly module_type
+
+	case "$module_type" in
+		('standalone')
+			printf '%s/module-templates/standalone-gradle.build.kts' "$root_dir_pathname"
+			;;
+		('composite')
+			printf '%s/module-templates/composite-gradle.build.kts' "$root_dir_pathname"
+			;;
+		('namespace')
+			printf '%s/module-templates/namespace-gradle.build.kts' "$root_dir_pathname"
+			;;
+		('service')
+			printf '%s/module-templates/service-gradle.build.kts' "$root_dir_pathname"
+			;;
+		('service_interface')
+			printf '%s/module-templates/service-interface-gradle.build.kts' "$root_dir_pathname"
+			;;
+		('service_implementation_standalone')
+			printf '%s/module-templates/service-implementation-standalone-gradle.build.kts' "$root_dir_pathname"
+			;;
+		('service_implementation_composite')
+			printf '%s/module-templates/service-implementation-composite-gradle.build.kts' "$root_dir_pathname"
+			;;
+		('service_wiring')
+			printf '%s/module-templates/service-wiring-gradle.build.kts' "$root_dir_pathname"
+			;;
+	esac
+}
+
+function should_module_contain_source_code() {
+	local module_type || return
+	module_type="$1" || return
+	readonly module_type || return
+
+	case "$module_type" in
+		('standalone') ;;
+		('composite')
+			return 32
+			;;
+		('namespace')
+			return 32
+			;;
+		('service')
+			return 32
+			;;
+		('service_interface') ;;
+		('service_implementation_standalone') ;;
+		('service_implementation_composite')
+			return 32
+			;;
+		('service_wiring') ;;
+	esac
+}
 
 printf 'include(\n'
-for module_path in "$@"; do
-	module_dir_pathname="$(printf '%s' "${module_path#:}" | sed -e s/:/'\/'/g)"
 
-	mkdir -p -- "$root_dir_pathname/$module_dir_pathname/src/main/kotlin/io/github/maybeashleyidk/discordbot/compoundzebracommunity"
+declare module_spec
+for module_spec in "${module_specs[@]}"; do
+	declare module_type
+	module_type="${module_spec%":${module_spec#*:}"}"
+
+	declare module_path
+	module_path="${module_spec#"$module_type:"}"
+
+	declare gradle_build_file_template_pathname
+	gradle_build_file_template_pathname="$(get_gradle_build_file_template_pathname_from_module_type "$module_type")"
+
+	declare module_dir_pathname
+	module_dir_pathname="$module_path"
+	module_dir_pathname="${module_dir_pathname#:}"
+	module_dir_pathname="${module_dir_pathname//':'/'/'}"
+
+	mkdir -p -- "$root_dir_pathname/$module_dir_pathname"
+
+	if should_module_contain_source_code "$module_type"; then
+		mkdir -p -- "$root_dir_pathname/$module_dir_pathname/src/main/kotlin/io/github/maybeashleyidk/discordbot/compoundzebracommunity"
+	fi
 
 	printf '/build/\n' > "$root_dir_pathname/$module_dir_pathname/.gitignore"
 	cp -- "$gradle_build_file_template_pathname" "$root_dir_pathname/$module_dir_pathname/build.gradle.kts"
 
 	printf '\t"%s",\n' "$module_path"
 
-	unset -v module_dir_pathname
-done; unset -v module_path
+	unset -v module_dir_pathname \
+	         gradle_build_file_template_pathname\
+	         module_path \
+	         module_type
+done
+unset -v module_spec
+
 printf ')\n'
+
+#endregion
